[package]
name = "ros2-sched-analysis"
version = "0.1.0"
authors = ["Björn Brandenburg <bbb@mpi-sws.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
itertools = "0.8.0"
